name: bagel
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.2.25=h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.16=h5eee18b_0
  - pip=25.1=pyhc872135_2
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.18=h1a3bd86_0
  - readline=8.2=h5eee18b_0
  - setuptools=78.1.1=py310h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h993c535_1
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
    - accelerate==1.8.1
    - addict==2.4.0
    - aiofiles==24.1.0
    - aiohappyeyeballs==2.6.1
    - aiohttp==3.13.2
    - aiosignal==1.4.0
    - annotated-types==0.7.0
    - anyio==4.9.0
    - asttokens==3.0.1
    - async-timeout==5.0.1
    - attrs==25.4.0
    - beautifulsoup4==4.14.2
    - bitsandbytes==0.46.1
    - certifi==2025.6.15
    - cfgv==3.5.0
    - charset-normalizer==3.4.2
    - click==8.2.1
    - colorama==0.4.6
    - coloredlogs==15.0.1
    - contourpy==1.3.2
    - controlnet-aux==0.0.10
    - cycler==0.12.1
    - datasets==4.0.0
    - decord==0.6.0
    - diffusers==0.30.0.dev0
    - dill==0.3.8
    - distlib==0.4.0
    - distro==1.9.0
    - easy-dwpose==1.0.2
    - einops==0.8.1
    - exceptiongroup==1.3.0
    - executing==2.2.1
    - fastapi==0.115.14
    - ffmpy==0.6.0
    - filelock==3.18.0
    - flash-attn==2.8.0.post2
    - flatbuffers==25.9.23
    - fonttools==4.58.5
    - frozenlist==1.8.0
    - fsspec==2025.3.0
    - ftfy==6.3.1
    - future==1.0.0
    - gdown==5.2.0
    - gitdb==4.0.12
    - gitpython==3.1.44
    - gradio==5.35.0
    - gradio-client==1.10.4
    - groovy==0.1.2
    - h11==0.16.0
    - hf-xet==1.2.0
    - httpcore==1.0.9
    - httpx==0.28.1
    - huggingface-hub==0.36.0
    - humanfriendly==10.0
    - identify==2.6.15
    - idna==3.10
    - imageio==2.37.2
    - imhist==0.0.4
    - importlib-metadata==8.7.0
    - imwatermark==0.0.2
    - iniconfig==2.3.0
    - invisible-watermark==0.2.0
    - jinja2==3.1.6
    - jiter==0.10.0
    - kiwisolver==1.4.8
    - kornia==0.8.2
    - kornia-rs==0.1.10
    - lazy-loader==0.4
    - lightning-utilities==0.15.2
    - llvmlite==0.45.1
    - lmdb==1.7.5
    - loguru==0.7.3
    - markdown-it-py==3.0.0
    - markupsafe==3.0.2
    - matplotlib==3.10.7
    - mdurl==0.1.2
    - mpmath==1.3.0
    - multidict==6.7.0
    - multiprocess==0.70.16
    - networkx==3.4.2
    - ninja==1.11.1.4
    - nodeenv==1.9.1
    - numba==0.62.1
    - numpy==1.26.4
    - nvidia-cublas-cu12==12.8.4.1
    - nvidia-cuda-cupti-cu12==12.8.90
    - nvidia-cuda-nvrtc-cu12==12.8.93
    - nvidia-cuda-runtime-cu12==12.8.90
    - nvidia-cudnn-cu12==9.10.2.21
    - nvidia-cufft-cu12==11.3.3.83
    - nvidia-cufile-cu12==1.13.1.3
    - nvidia-curand-cu12==10.3.9.90
    - nvidia-cusolver-cu12==11.7.3.90
    - nvidia-cusparse-cu12==12.5.8.93
    - nvidia-cusparselt-cu12==0.7.1
    - nvidia-ml-py==12.575.51
    - nvidia-nccl-cu12==2.27.3
    - nvidia-nvjitlink-cu12==12.8.93
    - nvidia-nvtx-cu12==12.8.90
    - onnxruntime-gpu==1.16.2
    - openai==1.93.0
    - openai-clip==1.0.1
    - opencv-python==4.11.0.86
    - opencv-python-headless==4.12.0.88
    - orjson==3.10.18
    - packaging==25.0
    - pandas==2.3.0
    - pillow==11.3.0
    - platformdirs==4.3.8
    - pluggy==1.6.0
    - pre-commit==4.4.0
    - propcache==0.4.1
    - protobuf==3.20.3
    - psutil==7.0.0
    - pyarrow==22.0.0
    - pydantic==2.11.7
    - pydantic-core==2.33.2
    - pydub==0.25.1
    - pygments==2.19.2
    - pynvml==12.0.0
    - pyparsing==3.2.3
    - pysocks==1.7.1
    - pytest==9.0.1
    - python-dateutil==2.9.0.post0
    - python-multipart==0.0.20
    - pytorch-fid==0.3.0
    - pytorch-lightning==2.5.6
    - pytz==2025.2
    - pywavelets==1.8.0
    - pyyaml==6.0.2
    - regex==2024.11.6
    - requests==2.32.3
    - rich==14.0.0
    - ruff==0.12.2
    - safehttpx==0.1.6
    - safetensors==0.4.5
    - scikit-image==0.24.0
    - scipy==1.15.3
    - semantic-version==2.10.0
    - sentencepiece==0.1.99
    - sentry-sdk==2.32.0
    - shellingham==1.5.4
    - six==1.17.0
    - smmap==5.0.2
    - sniffio==1.3.1
    - soupsieve==2.8
    - starlette==0.46.2
    - sympy==1.14.0
    - taming-transformers==0.0.1
    - taming-transformers-rom1504==0.0.6
    - tifffile==2025.5.10
    - timm==1.0.22
    - tokenizers==0.22.1
    - tomlkit==0.13.3
    - torch==2.8.0+cu128
    - torchaudio==2.8.0+cu128
    - torchmetrics==1.8.2
    - torchvision==0.23.0+cu128
    - tqdm==4.67.1
    - transformers==4.57.1
    - triton==3.4.0
    - typer==0.16.0
    - typer-slim==0.20.0
    - typing-extensions==4.14.0
    - typing-inspection==0.4.1
    - tzdata==2025.2
    - urllib3==2.5.0
    - uvicorn==0.35.0
    - virtualenv==20.35.4
    - wandb==0.21.0
    - wcwidth==0.2.14
    - websockets==15.0.1
    - xlsxwriter==3.2.5
    - xxhash==3.6.0
    - yapf==0.43.0
    - yarl==1.22.0
    - zipp==3.23.0
prefix: /home/jaesang/.conda/envs/bagel
